namespace FreeGLBA;

#region Glba External API DataObjects
// ============================================================================
// GLBA API DATA TRANSFER OBJECTS
// Generated by Entity Builder Wizard
// ============================================================================

public partial class DataObjects
{
    /// <summary>Incoming event from external source system.</summary>
    public class GlbaEventRequest
    {
        public string? SourceEventId { get; set; }
        public DateTime AccessedAt { get; set; }
        public string UserId { get; set; } = string.Empty;
        public string? UserName { get; set; }
        public string? UserEmail { get; set; }
        public string? UserDepartment { get; set; }
        /// <summary>
        /// Subject ID for single-subject access. For bulk access, use SubjectIds instead
        /// and set this to "BULK" or leave empty.
        /// </summary>
        public string SubjectId { get; set; } = string.Empty;
        public string? SubjectType { get; set; }
        /// <summary>
        /// List of subject IDs for bulk access (e.g., CSV export containing hundreds of students).
        /// When provided, SubjectCount will be set automatically. Each subject will be tracked
        /// in the Data Subjects table for audit purposes.
        /// </summary>
        public List<string>? SubjectIds { get; set; }
        public string? DataCategory { get; set; }
        public string AccessType { get; set; } = string.Empty;
        public string? Purpose { get; set; }
        public string? IpAddress { get; set; }
        public string? AdditionalData { get; set; }
        /// <summary>
        /// Copy of the privacy notice/agreement text shown to the user at time of access.
        /// Include this to document what disclosure the user acknowledged before accessing data.
        /// </summary>
        public string? AgreementText { get; set; }
        /// <summary>
        /// When the user acknowledged the privacy agreement. Defaults to AccessedAt if not provided.
        /// </summary>
        public DateTime? AgreementAcknowledgedAt { get; set; }
    }

    /// <summary>Response after processing an event.</summary>
    public class GlbaEventResponse
    {
        public Guid? EventId { get; set; }
        public DateTime ReceivedAt { get; set; } = DateTime.UtcNow;
        public string Status { get; set; } = string.Empty; // accepted, duplicate, error
        public string? Message { get; set; }
        /// <summary>Number of data subjects affected by this event.</summary>
        public int SubjectCount { get; set; }
    }

    /// <summary>Response after processing a batch of events.</summary>
    public class GlbaBatchResponse
    {
        public int Accepted { get; set; }
        public int Rejected { get; set; }
        public int Duplicate { get; set; }
        public List<GlbaBatchError> Errors { get; set; } = new();
    }

    /// <summary>Error detail for a single event in a batch.</summary>
    public class GlbaBatchError
    {
        public int Index { get; set; }
        public string Error { get; set; } = string.Empty;
    }

    /// <summary>Dashboard statistics.</summary>
    public class GlbaStats
    {
        public long Today { get; set; }
        public long ThisWeek { get; set; }
        public long ThisMonth { get; set; }
        /// <summary>Total number of data subjects in the system.</summary>
        public long TotalSubjects { get; set; }
        /// <summary>Subjects accessed today.</summary>
        public long SubjectsToday { get; set; }
        /// <summary>Subjects accessed this week.</summary>
        public long SubjectsThisWeek { get; set; }
        /// <summary>Subjects accessed this month.</summary>
        public long SubjectsThisMonth { get; set; }
        /// <summary>Total unique accessors (users who have accessed data).</summary>
        public long TotalAccessors { get; set; }
        public Dictionary<string, long> ByCategory { get; set; } = new();
        public Dictionary<string, long> ByAccessType { get; set; } = new();
    }

    /// <summary>Accessor (user who accessed data) summary for reporting.</summary>
    public class AccessorSummary
    {
        public string UserId { get; set; } = string.Empty;
        public string? UserName { get; set; }
        public string? UserEmail { get; set; }
        public string? UserDepartment { get; set; }
        public int TotalAccesses { get; set; }
        public int UniqueSubjectsAccessed { get; set; }
        public int ExportCount { get; set; }
        public int ViewCount { get; set; }
        public DateTime FirstAccessAt { get; set; }
        public DateTime LastAccessAt { get; set; }
    }

    /// <summary>Filter for accessor queries.</summary>
    public class AccessorFilter
    {
        public string? Search { get; set; }
        public string? Department { get; set; }
        // Advanced filters
        public int? MinTotalAccesses { get; set; }
        public int? MaxTotalAccesses { get; set; }
        public int? MinUniqueSubjects { get; set; }
        public int? MaxUniqueSubjects { get; set; }
        public int? MinExportCount { get; set; }
        public int? MaxExportCount { get; set; }
        public int? MinViewCount { get; set; }
        public int? MaxViewCount { get; set; }
        public DateTime? LastAccessAfter { get; set; }
        public DateTime? LastAccessBefore { get; set; }
        // Sort and pagination
        public string SortColumn { get; set; } = "TotalAccesses";
        public bool SortDescending { get; set; } = true;
        public int Page { get; set; } = 1;
        public int PageSize { get; set; } = 25;
        public int Skip => (Page - 1) * PageSize;
    }

    /// <summary>Result of accessor query.</summary>
    public class AccessorFilterResult
    {
        public List<AccessorSummary> Records { get; set; } = new();
        public int TotalRecords { get; set; }
        public int Page { get; set; }
        public int PageSize { get; set; }
        public int TotalPages => (int)Math.Ceiling((double)TotalRecords / PageSize);
    }
}

#endregion
