namespace FreeGLBA;

#region FreeGLBA API Endpoints
// ============================================================================
// FREEGLBA PROJECT - API Endpoint Constants
// Generated by Entity Builder Wizard
// ============================================================================

public partial class DataObjects
{
    public static partial class Endpoints
    {
        public static class FreeGLBA
        {
            // ============================================================
            // SOURCESYSTEM ENDPOINTS
            // ============================================================

            /// <summary>Get filtered list of SourceSystems</summary>
            public const string GetSourceSystems = "api/Data/GetSourceSystems";

            /// <summary>Get single SourceSystem by ID</summary>
            public const string GetSourceSystem = "api/Data/GetSourceSystem";

            /// <summary>Get SourceSystem lookup list for dropdowns</summary>
            public const string GetSourceSystemLookups = "api/Data/GetSourceSystemLookups";

            /// <summary>Create or update SourceSystem</summary>
            public const string SaveSourceSystem = "api/Data/SaveSourceSystem";

            /// <summary>Delete SourceSystem by ID</summary>
            public const string DeleteSourceSystem = "api/Data/DeleteSourceSystem";

            // ============================================================
            // ACCESSEVENT ENDPOINTS
            // ============================================================

            /// <summary>Get filtered list of AccessEvents</summary>
            public const string GetAccessEvents = "api/Data/GetAccessEvents";

            /// <summary>Get single AccessEvent by ID</summary>
            public const string GetAccessEvent = "api/Data/GetAccessEvent";

            /// <summary>Get AccessEvent lookup list for dropdowns</summary>
            public const string GetAccessEventLookups = "api/Data/GetAccessEventLookups";

            /// <summary>Create or update AccessEvent</summary>
            public const string SaveAccessEvent = "api/Data/SaveAccessEvent";

            /// <summary>Delete AccessEvent by ID</summary>
            public const string DeleteAccessEvent = "api/Data/DeleteAccessEvent";

            // ============================================================
            // DATASUBJECT ENDPOINTS
            // ============================================================

            /// <summary>Get filtered list of DataSubjects</summary>
            public const string GetDataSubjects = "api/Data/GetDataSubjects";

            /// <summary>Get single DataSubject by ID</summary>
            public const string GetDataSubject = "api/Data/GetDataSubject";

            /// <summary>Get DataSubject lookup list for dropdowns</summary>
            public const string GetDataSubjectLookups = "api/Data/GetDataSubjectLookups";

            /// <summary>Create or update DataSubject</summary>
            public const string SaveDataSubject = "api/Data/SaveDataSubject";

            /// <summary>Delete DataSubject by ID</summary>
            public const string DeleteDataSubject = "api/Data/DeleteDataSubject";

            // ============================================================
            // COMPLIANCEREPORT ENDPOINTS
            // ============================================================

            /// <summary>Get filtered list of ComplianceReports</summary>
            public const string GetComplianceReports = "api/Data/GetComplianceReports";

            /// <summary>Get single ComplianceReport by ID</summary>
            public const string GetComplianceReport = "api/Data/GetComplianceReport";

            /// <summary>Get ComplianceReport lookup list for dropdowns</summary>
            public const string GetComplianceReportLookups = "api/Data/GetComplianceReportLookups";

            /// <summary>Create or update ComplianceReport</summary>
            public const string SaveComplianceReport = "api/Data/SaveComplianceReport";

            /// <summary>Delete ComplianceReport by ID</summary>
            public const string DeleteComplianceReport = "api/Data/DeleteComplianceReport";

            // ============================================================
            // ACCESSOR (USER WHO ACCESSED DATA) ENDPOINTS
            // ============================================================

            /// <summary>Get filtered list of Accessors (users who have accessed data)</summary>
            public const string GetAccessors = "api/Data/GetAccessors";

            /// <summary>Get top accessors for dashboard</summary>
            public const string GetTopAccessors = "api/Data/GetTopAccessors";

        }
    }
}

#endregion
