namespace FreeGLBA;

// ============================================================================
// FREEGLBA PROJECT - IDataAccess Extension
// Interface method signatures for generated entities
// Generated by Entity Builder Wizard
// ============================================================================

public partial interface IDataAccess
{
    // SourceSystem methods
    Task<DataObjects.SourceSystemFilterResult> GetSourceSystemsAsync(DataObjects.SourceSystemFilter filter);
    Task<DataObjects.SourceSystem?> GetSourceSystemAsync(Guid id);
    Task<List<DataObjects.SourceSystemLookup>> GetSourceSystemLookupsAsync();
    Task<DataObjects.SourceSystem?> SaveSourceSystemAsync(DataObjects.SourceSystem dto);
    Task<bool> DeleteSourceSystemAsync(Guid id);

    // AccessEvent methods
    Task<DataObjects.AccessEventFilterResult> GetAccessEventsAsync(DataObjects.AccessEventFilter filter);
    Task<DataObjects.AccessEvent?> GetAccessEventAsync(Guid id);
    Task<List<DataObjects.AccessEventLookup>> GetAccessEventLookupsAsync();
    Task<DataObjects.AccessEvent?> SaveAccessEventAsync(DataObjects.AccessEvent dto);
    Task<bool> DeleteAccessEventAsync(Guid id);

    // DataSubject methods
    Task<DataObjects.DataSubjectFilterResult> GetDataSubjectsAsync(DataObjects.DataSubjectFilter filter);
    Task<DataObjects.DataSubject?> GetDataSubjectAsync(Guid id);
    Task<List<DataObjects.DataSubjectLookup>> GetDataSubjectLookupsAsync();
    Task<DataObjects.DataSubject?> SaveDataSubjectAsync(DataObjects.DataSubject dto);
    Task<bool> DeleteDataSubjectAsync(Guid id);

    // ComplianceReport methods
    Task<DataObjects.ComplianceReportFilterResult> GetComplianceReportsAsync(DataObjects.ComplianceReportFilter filter);
    Task<DataObjects.ComplianceReport?> GetComplianceReportAsync(Guid id);
    Task<List<DataObjects.ComplianceReportLookup>> GetComplianceReportLookupsAsync();
    Task<DataObjects.ComplianceReport?> SaveComplianceReportAsync(DataObjects.ComplianceReport dto);
    Task<bool> DeleteComplianceReportAsync(Guid id);

    // API Request Logging methods
    Task<Guid> CreateApiLogAsync(EFModels.EFModels.ApiRequestLogItem log);
    Task<DataObjects.ApiLogFilterResult> GetApiLogsAsync(DataObjects.ApiLogFilter filter);
    Task<DataObjects.ApiRequestLog?> GetApiLogAsync(Guid id);
    Task<DataObjects.ApiLogDashboardStats> GetApiLogDashboardStatsAsync(DateTime from, DateTime to);

    // Body Logging Configuration methods
    Task<EFModels.EFModels.BodyLoggingConfigItem?> GetBodyLoggingConfigAsync(Guid sourceSystemId);
    Task<List<DataObjects.BodyLoggingConfig>> GetBodyLoggingConfigsAsync();
    Task<DataObjects.BodyLoggingConfig> EnableBodyLoggingAsync(Guid sourceSystemId, Guid enabledByUserId, string enabledByUserName, int durationHours, string reason);
    Task<bool> DisableBodyLoggingAsync(Guid configId);
}
