using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace FreeGLBA.Controllers;

// ============================================================================
// GLBA EXTERNAL API CONTROLLER
// Receives events from external source systems via API key authentication.
// Generated by FreeManager for template: FreeAudit
// ============================================================================

/// <summary>
/// GLBA Compliance API - Log and query access to protected financial information
/// </summary>
[ApiController]
[Route("api/glba")]
[ApiRequestLogging]
[Produces("application/json")]
public class GlbaController : ControllerBase
{
    private readonly IDataAccess _da;

    public GlbaController(IDataAccess da)
    {
        _da = da;
    }

    // ============================================================
    // EXTERNAL ENDPOINTS (API Key Auth via middleware)
    // ============================================================

    /// <summary>
    /// Log a single access event
    /// </summary>
    /// <remarks>
    /// Records a single instance of data access for GLBA compliance tracking.
    /// 
    /// **Authentication:** API Key (Bearer token in Authorization header)
    /// 
    /// **Example request:**
    /// ```json
    /// {
    ///   "userId": "jsmith",
    ///   "userName": "John Smith",
    ///   "subjectId": "STU-12345",
    ///   "accessType": "View",
    ///   "purpose": "Reviewing financial aid application"
    /// }
    /// ```
    /// </remarks>
    /// <param name="request">The access event details</param>
    /// <returns>Event confirmation with assigned ID</returns>
    /// <response code="201">Event recorded successfully</response>
    /// <response code="400">Validation error - check required fields</response>
    /// <response code="401">Invalid or missing API key</response>
    /// <response code="409">Duplicate event (same SourceEventId already exists)</response>
    [HttpPost("events")]
    [Tags("External - Event Logging")]
    [ProducesResponseType(typeof(DataObjects.GlbaEventResponse), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(typeof(DataObjects.GlbaEventResponse), StatusCodes.Status409Conflict)]
    public async Task<ActionResult<DataObjects.GlbaEventResponse>> PostEvent(
        [FromBody] DataObjects.GlbaEventRequest request)
    {
        // Get source system from middleware (set by ApiKeyMiddleware)
        var source = HttpContext.Items["SourceSystem"] as DataObjects.SourceSystem;
        if (source == null)
        {
            return Unauthorized(new { error = "invalid_api_key", message = "API key is invalid or inactive" });
        }

        var result = await _da.ProcessGlbaEventAsync(request, source.SourceSystemId);

        return result.Status switch
        {
            "accepted" => Created($"/api/glba/events/{result.EventId}", result),
            "duplicate" => Conflict(result),
            _ => BadRequest(result)
        };
    }

    /// <summary>
    /// Log multiple access events in a single request
    /// </summary>
    /// <remarks>
    /// Submit up to 1000 events in a single batch request. Useful for:
    /// - Migrating historical data
    /// - Batch processing from external systems
    /// - High-volume event logging
    /// 
    /// **Authentication:** API Key (Bearer token in Authorization header)
    /// 
    /// Each event is processed independently - partial success is possible.
    /// </remarks>
    /// <param name="events">List of access events (max 1000)</param>
    /// <returns>Batch processing results with accepted/rejected counts</returns>
    /// <response code="200">Batch processed (check accepted/rejected counts)</response>
    /// <response code="400">Batch too large (over 1000 events)</response>
    /// <response code="401">Invalid or missing API key</response>
    [HttpPost("events/batch")]
    [Tags("External - Event Logging")]
    [ProducesResponseType(typeof(DataObjects.GlbaBatchResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<ActionResult<DataObjects.GlbaBatchResponse>> PostBatch(
        [FromBody] List<DataObjects.GlbaEventRequest> events)
    {
        var source = HttpContext.Items["SourceSystem"] as DataObjects.SourceSystem;
        if (source == null)
        {
            return Unauthorized(new { error = "invalid_api_key", message = "API key is invalid or inactive" });
        }

        if (events.Count > 1000)
        {
            return BadRequest(new { error = "batch_too_large", message = "Maximum 1000 events per batch" });
        }

        var result = await _da.ProcessGlbaBatchAsync(events, source.SourceSystemId);
        return Ok(result);
    }

    // ============================================================
    // INTERNAL ENDPOINTS (User Auth)
    // ============================================================

    /// <summary>
    /// Get dashboard summary statistics
    /// </summary>
    /// <remarks>
    /// Returns aggregate statistics for the GLBA dashboard including:
    /// - Event counts (today, this week, this month)
    /// - Subject counts (unique individuals whose data was accessed)
    /// - Breakdowns by category and access type
    /// 
    /// **Authentication:** User JWT (not API key)
    /// </remarks>
    /// <response code="200">Statistics retrieved successfully</response>
    /// <response code="401">Not authenticated</response>
    [HttpGet("stats/summary")]
    [Authorize]
    [Tags("Internal - Dashboard")]
    [ProducesResponseType(typeof(DataObjects.GlbaStats), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<ActionResult<DataObjects.GlbaStats>> GetStats()
    {
        var stats = await _da.GetGlbaStatsAsync();
        return Ok(stats);
    }

    /// <summary>
    /// Get recent access events
    /// </summary>
    /// <remarks>
    /// Returns the most recent access events for the dashboard feed.
    /// 
    /// **Authentication:** User JWT (not API key)
    /// </remarks>
    /// <param name="limit">Maximum events to return (default 50, max 100)</param>
    /// <response code="200">Events retrieved successfully</response>
    /// <response code="401">Not authenticated</response>
    [HttpGet("events/recent")]
    [Authorize]
    [Tags("Internal - Dashboard")]
    [ProducesResponseType(typeof(List<DataObjects.AccessEvent>), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<ActionResult<List<DataObjects.AccessEvent>>> GetRecentEvents(
        [FromQuery] int limit = 50)
    {
        var events = await _da.GetRecentAccessEventsAsync(Math.Min(limit, 100));
        return Ok(events);
    }

    /// <summary>
    /// Get access events for a specific data subject
    /// </summary>
    /// <remarks>
    /// Returns all access events where the specified subject's data was accessed.
    /// Useful for auditing who has accessed a particular individual's information.
    /// 
    /// **Authentication:** User JWT (not API key)
    /// </remarks>
    /// <param name="subjectId">The external ID of the data subject (e.g., student ID)</param>
    /// <param name="limit">Maximum events to return (default 100, max 500)</param>
    /// <response code="200">Events retrieved successfully</response>
    /// <response code="401">Not authenticated</response>
    [HttpGet("subjects/{subjectId}/events")]
    [Authorize]
    [Tags("Internal - Queries")]
    [ProducesResponseType(typeof(List<DataObjects.AccessEvent>), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<ActionResult<List<DataObjects.AccessEvent>>> GetSubjectEvents(
        string subjectId, [FromQuery] int limit = 100)
    {
        var events = await _da.GetAccessEventsBySubjectAsync(subjectId, Math.Min(limit, 500));
        return Ok(events);
    }

    /// <summary>
    /// Get a single access event by ID
    /// </summary>
    /// <remarks>
    /// Retrieves full details of a specific access event.
    /// 
    /// **Authentication:** User JWT (not API key)
    /// </remarks>
    /// <param name="eventId">The unique identifier of the event</param>
    /// <response code="200">Event retrieved successfully</response>
    /// <response code="401">Not authenticated</response>
    /// <response code="404">Event not found</response>
    [HttpGet("events/{eventId:guid}")]
    [Authorize]
    [Tags("Internal - Queries")]
    [ProducesResponseType(typeof(DataObjects.AccessEvent), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<DataObjects.AccessEvent>> GetEvent(Guid eventId)
    {
        var evt = await _da.GetAccessEventAsync(eventId);
        if (evt == null) return NotFound();
        return Ok(evt);
    }

    /// <summary>
    /// Get status of all source systems
    /// </summary>
    /// <remarks>
    /// Returns information about all registered source systems including:
    /// - Name and display name
    /// - Active status
    /// - Last event received timestamp
    /// - Total event count
    /// 
    /// **Authentication:** User JWT (not API key)
    /// </remarks>
    /// <response code="200">Source systems retrieved successfully</response>
    /// <response code="401">Not authenticated</response>
    [HttpGet("sources/status")]
    [Authorize]
    [Tags("Internal - Dashboard")]
    [ProducesResponseType(typeof(List<DataObjects.SourceSystem>), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<ActionResult<List<DataObjects.SourceSystem>>> GetSourceStatus()
    {
        var sources = await _da.GetSourceSystemsAsync();
        return Ok(sources);
    }

    /// <summary>
    /// Get top data accessors
    /// </summary>
    /// <remarks>
    /// Returns the users who have accessed the most protected data, including:
    /// - Total access count
    /// - Unique subjects accessed
    /// - Export vs view breakdown
    /// 
    /// Useful for compliance monitoring and identifying unusual access patterns.
    /// 
    /// **Authentication:** User JWT (not API key)
    /// </remarks>
    /// <param name="limit">Maximum accessors to return (default 10, max 50)</param>
    /// <response code="200">Accessors retrieved successfully</response>
    /// <response code="401">Not authenticated</response>
    [HttpGet("accessors/top")]
    [Authorize]
    [Tags("Internal - Dashboard")]
    [ProducesResponseType(typeof(List<DataObjects.AccessorSummary>), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<ActionResult<List<DataObjects.AccessorSummary>>> GetTopAccessors(
        [FromQuery] int limit = 10)
    {
        var accessors = await _da.GetTopAccessorsAsync(Math.Min(limit, 50));
        return Ok(accessors);
    }
}
